test:maxSeq.o test-subseq.o
	gcc -o test maxSeq.o test-subseq.o
maxSeq:maxSeq.c
	gcc -o maxSeq -pedantic -std=gnu99 -Wall -Werror maxSeq.c
test-subseq:test-subseq.c
	gcc -o test-subseq -pedantic -std=gnu99 test-subseq.c

